[project]
name = "tools-rust-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lep511", email = "estebanpbuday@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "strands-agents>=1.56.0",
]

[project.scripts]
tools-rust-calculator = "tools_rust_calculator:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
