[project]
name = "harness-strand-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lep511", email = "estebanpbuday@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.102",
    "rich>=15.0.0",
    "strands-harness>=0.1.2",
]

[project.scripts]
harness-strand-example = "harness_strand_example:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
