[project]
name = "guardrails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Workshop User", email = "workshopuser@example.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
guardrails = "guardrails:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
